INSERT INTO tasks (description, title) VALUES
                                           ('Create a list and buy all necessary groceries for the week.', 'Grocery Shopping'),
                                           ('Prepare a presentation for the weekly team meeting.', 'Work Meeting'),
                                           ('Call the clinic and schedule an annual check-up.', 'Doctor Appointment'),
                                           ('Read 50 pages of the selected book.', 'Reading Book'),
                                           ('Spend 1 hour at the gym following the workout plan.', 'Workout'),
                                           ('Prepare for the exam by studying 3 chapters from the textbook.', 'Study Session'),
                                           ('Analyze monthly expenses and plan the budget for the next month.', 'Budget Planning'),
                                           ('Do a thorough cleaning of the entire apartment.', 'Apartment Cleaning'),
                                           ('Write and edit an article for the blog.', 'Writing Article'),
                                           ('Find and buy a gift for a friend’s birthday.', 'Gift Shopping'),
                                           ('Update and improve your resume.', 'Resume Update'),
                                           ('Attend a yoga class.', 'Yoga Session'),
                                           ('Watch a recommended movie and write a review.', 'Watching Movie'),
                                           ('Write and send 5 business letters.', 'Sending Letters'),
                                           ('Plant new flowers in the garden.', 'Planting Flowers'),
                                           ('Spend 1 hour learning a new language.', 'Language Learning'),
                                           ('Develop a plan for a new project at work.', 'Project Planning'),
                                           ('Visit your parents and spend the evening with them.', 'Visiting Parents'),
                                           ('Wash and clean the car.', 'Car Cleaning'),
                                           ('Practice playing the guitar.', 'Playing Instrument'),
                                           ('Participate in a volunteer activity.', 'Volunteering'),
                                           ('Cook a new dish following a recipe.', 'Cooking New Recipe'),
                                           ('Update all software on the computer.', 'Software Update'),
                                           ('Walk the dog and feed it.', 'Pet Care'),
                                           ('Organize photos and create an album.', 'Creating Photo Album'),
                                           ('Install new shelves in the room.', 'Installing Shelves'),
                                           ('Start a new hobby, such as drawing.', 'New Hobby'),
                                           ('Plan and organize a party with friends.', 'Organizing Party'),
                                           ('Update all passwords for personal accounts.', 'Changing Passwords'),
                                           ('Participate in a cooking workshop.', 'Attending Workshop'),
                                           ('Do a wardrobe audit and get rid of unnecessary clothes.', 'Wardrobe Cleaning');
